<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4047" started-at="2018-10-16T20:51:33Z" finished-at="2018-10-16T20:51:37Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4047" started-at="2018-10-16T20:51:33Z" finished-at="2018-10-16T20:51:37Z">
      <class name="com.gurantors.GuarantorsApi.AppTest">
        <test-method status="PASS" signature="Post200TestWithNegativeNumbers()[pri:0, instance:com.gurantors.GuarantorsApi.AppTest@7ac7a4e4]" name="Post200TestWithNegativeNumbers" duration-ms="3030" started-at="2018-10-16T16:51:33Z" finished-at="2018-10-16T16:51:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Post200TestWithNegativeNumbers -->
        <test-method status="PASS" signature="Post200TestWithWholeNumbers()[pri:0, instance:com.gurantors.GuarantorsApi.AppTest@7ac7a4e4]" name="Post200TestWithWholeNumbers" duration-ms="523" started-at="2018-10-16T16:51:36Z" finished-at="2018-10-16T16:51:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Post200TestWithWholeNumbers -->
        <test-method status="FAIL" signature="Post400Test()[pri:0, instance:com.gurantors.GuarantorsApi.AppTest@7ac7a4e4]" name="Post400Test" duration-ms="461" started-at="2018-10-16T16:51:37Z" finished-at="2018-10-16T16:51:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Status code validation expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Status code validation expected [400] but found [200]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.gurantors.GuarantorsApi.AppTest.Post400Test(AppTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Post400Test -->
      </class> <!-- com.gurantors.GuarantorsApi.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
